---
- name: Cambiar fondo de pantalla con Ansible
  hosts: localhost
  become: yes
  tasks:
    - name: Copiar script para cambiar el fondo
      copy:
        src: set-wallpaper.sh
        dest: /usr/local/bin/set-wallpaper.sh
        mode: '0755'

    - name: Crear carpeta autostart si no existe
      file:
        path: /home/{{ ansible_user_id }}/.config/autostart
        state: directory
        mode: '0755'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"

    - name: Copiar archivo .desktop para autostart
      copy:
        src: wallpaper.desktop
        dest: /home/{{ ansible_user_id }}/.config/autostart/wallpaper.desktop
        mode: '0644'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
